### ISSUE TITLE
processMessage failed: Error: TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by poppahorse** [AppGyver/PushNotifications#10]
```javascript
processMessage failed: Error: TypeError: undefined is not a function cordova.js:1044
processMessage failed: Stack: TypeError: undefined is not a function
    at registrationHandler (http://localhost/app/settings.js:111:19)
    at Object.cordova.callbackFromNative (http://localhost/cordova.js:292:54)
    at processMessage (http://localhost/cordova.js:1039:21)
    at Function.androidExec.processMessages (http://localhost/cordova.js:1076:13)
    at pollOnce (http://localhost/cordova.js:944:17)
    at pollOnceFromOnlineEvent (http://localhost/cordova.js:939:5) cordova.js:1045
processMessage failed: Message: S01 PushPlugin1230508099 sAPA91bHIP6LrQF431LNbnyQURXHJnzVhShJVVwcf__ai3MeyDYc7MX6pO_S_RGt6UdSQzMxodtCgT68OCSqcI47QrnEn9iVXAtVnzkrn3NxnJj_jm3YMhHGBVgaKltXX7bijfigo6CJIx6L1Tedg-vUfUI7vSFFnsGq_0aglmLL9j9tIC_fgOGY cordova.js:1046
```
That line 111 of settings.js corresponds to the below, the `pushNotification.onMessageInForeground(` section

Its like the pushNotification js is not loading. Then when I reload the view in chrome debugger the error goes away, but I am getting zero output to the console when a push comes in, be it foreground or background

```javascript
var pushNotification;

document.addEventListener("deviceready", function() {
  pushNotification = window.plugins.pushNotification;
  
  pushNotification.register(
		    registrationHandler,
		    errorHandler, {
		        //android options
		        "senderID":"xxxxxxxxxxxx",
		        //ios options
		        "badge":"true",
		        "sound":"true",
		        "alert":"true"
		        });
});

function errorHandler (error) {
    alert('error = ' + error);
}

function registrationHandler (deviceToken) {
	console.log('deviceToken = ' + deviceToken);
    //save the deviceToken / registration ID to your Push Notification Server

	pushNotification.onMessageInForeground(
	    messageInForegroundHandler,
	    errorHandler);

	pushNotification.onMessageInBackground(
	    messageInBackgroundHandler,
	    errorHandler);

}



function messageInForegroundHandler (notification) {

    //handle the contents of the notification
    console.log(notification.message || notification.alert);

    if ( event.sound ) {
        var snd = new Media(event.sound);
        snd.play();
    }

    if ( event.badge ) {
        
    }
    console.log(notification);
}

function messageInBackgroundHandler (notification) {
    if (notification.coldstart) {
        // ios, this is always true
        // the application was started by the user tapping on the notification
    }
    else {
        //this notification was delived while the app was in background
    }

    //handle the contents of the notification
    var message = notification.message || notification.alert;
    console.log(notification);

}
```

**Comment by fidoboy** [comment]
Can confirm this issue. Weird is that sometimes notification is being displayed on task bar but not on app (console output). 

Where are you using your event listeners? Are these functions inside angular or other events?

**Comment by fidoboy** [comment]
I'm sorry, my mistake, right syntax is `notification.aps.alert` or `notification.aps.sound` for standard properties and `notification.mycustomvar` to access to custom variables.

**Comment by harsaharsa** [comment]
It seems like an issue with the JS code, not push plugin. Not sure where it's going wonky – maybe the variables are not being exposed correctly and `pushNotification` is undefined? In any case, can't replicate any `undefined` errors when the push plugin API calls are made in the correct order, so closing this.
